/* prettier-ignore */
/* eslint-disable */
// Generated by elegant-router
// Read more: https://github.com/mufeng889/elegant-router
// Vue auto route: https://github.com/soybeanjs/elegant-router
// 请不要手动修改此文件，否则会导致优雅路由无法正常工作
// 如果需要修改，请在优雅路由配置文件中进行修改
// 这是自动生成的文件，请不要手动修改



export const layouts = {
  "(base)": () => import("@/pages/(base)/layout.tsx"),
  "(blank)": () => import("@/pages/(blank)/layout.tsx"),
  "(blank)_login": () => import("@/pages/(blank)/login/layout.tsx"),
};

export const pages = {
  "(base)_home": () => import("@/pages/(base)/home/index.tsx"),
  "(base)_manage_menu": () => import("@/pages/(base)/manage/menu/index.tsx"),
  "(base)_multi-menu_first_child": () => import("@/pages/(base)/multi-menu/first/child/index.tsx"),
  "(base)_multi-menu_second_child_home": () => import("@/pages/(base)/multi-menu/second/child/home/index.tsx"),
  "(base)_user-center": () => import("@/pages/(base)/user-center/index.tsx"),
  "(blank)_login_code-login": () => import("@/pages/(blank)/login/code-login/index.tsx"),
  "(blank)_login": () => import("@/pages/(blank)/login/index.tsx"),
  "(blank)_login_register": () => import("@/pages/(blank)/login/register/index.tsx"),
  "(blank)_login_reset-pwd": () => import("@/pages/(blank)/login/reset-pwd/index.tsx"),
  "403": () => import("@/pages/403.tsx"),
  "404": () => import("@/pages/404.tsx"),
  "500": () => import("@/pages/500.tsx"),
  "root": () => import("@/pages/index.tsx"),
};

export const errors = {
  "root": () => import("@/pages/error.tsx"),
};

export const configs = {
  "(base)_home": () => import("@/pages/(base)/home/config.ts"),
  "(base)_manage": () => import("@/pages/(base)/manage/config.ts"),
  "(base)_manage_menu": () => import("@/pages/(base)/manage/menu/config.ts"),
  "(base)_multi-menu": () => import("@/pages/(base)/multi-menu/config.ts"),
  "(base)_multi-menu_first_child": () => import("@/pages/(base)/multi-menu/first/child/config.ts"),
  "(base)_multi-menu_first": () => import("@/pages/(base)/multi-menu/first/config.ts"),
  "(base)_multi-menu_second_child": () => import("@/pages/(base)/multi-menu/second/child/config.ts"),
  "(base)_multi-menu_second_child_home": () => import("@/pages/(base)/multi-menu/second/child/home/config.ts"),
  "(base)_multi-menu_second": () => import("@/pages/(base)/multi-menu/second/config.ts"),
  "(base)_user-center": () => import("@/pages/(base)/user-center/config.ts"),
  "(blank)_login_code-login": () => import("@/pages/(blank)/login/code-login/config.ts"),
  "(blank)_login": () => import("@/pages/(blank)/login/config.ts"),
  "(blank)_login_register": () => import("@/pages/(blank)/login/register/config.ts"),
  "(blank)_login_reset-pwd": () => import("@/pages/(blank)/login/reset-pwd/config.ts"),
  "root": () => import("@/pages/config.ts"),
};

export const loadings = {
  "root": "/src/pages/loading.tsx",
};
